name: Publish NuGet
on:
  push:
    branches:
    - master
jobs:
  publish:
    name: publish to nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
  
      - name: Publish if version is updated
        uses: rohith/publish-nuget@v1
        with: 
          project_dir: src
