name: Publish CodeMonkeysMVVM (branch 'master')
on:
  push:
    branches:
    - master
jobs:
  publish:
    name: Publish to NuGet
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Publish CodeMonkeys.DependencyInjection
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/DependencyInjection/DependencyInjection/DependencyInjection.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.DependencyInjection
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.DependencyInjection.DryIoC
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/DependencyInjection/DependencyInjection.DryIoC/DependencyInjection.DryIoC.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.DependencyInjection.DryIoC
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.DependencyInjection.Ninject
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/DependencyInjection/DependencyInjection.Ninject/DependencyInjection.Ninject.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.DependencyInjection.Ninject
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Dialogs
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Dialogs/Dialogs/Dialogs.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Dialogs
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Dialogs.Xamarin.Forms
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Dialogs/Dialogs.Xamarin.Forms/Dialogs.Xamarin.Forms.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Dialogs.Xamarin.Forms
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Logging
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Logging/Logging/Logging.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Logging
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Logging.Batching
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Logging/Logging.Batching/Logging.Batching.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Logging.Batching
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Logging.Console
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Logging/Logging.Console/Logging.Console.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Logging.Console
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Logging.Debug
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Logging/Logging.Debug/Logging.Debug.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Logging.Debug
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Logging.File
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Logging/Logging.File/Logging.File.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Logging.File
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Navigation.WPF
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Navigation/WPF/Navigation.WPF/Navigation.WPF.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Navigation.Navigation.WPF
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Navigation.WPF.Interfaces
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Navigation/WPF/Navigation.WPF.Interfaces/Navigation.WPF.Interfaces.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Navigation.Navigation.WPF.Interfaces
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Navigation.Xamarin.Forms
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Navigation/Xamarin.Forms/Navigation.Xamarin.Forms/Navigation.Xamarin.Forms.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Navigation.Xamarin.Forms
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Navigation.Xamarin.Forms.Interfaces
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Navigation/Xamarin.Forms/Navigation.Xamarin.Forms.Interfaces/Navigation.Xamarin.Forms.Interfaces.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Navigation.Xamarin.Forms.Interfaces
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Navigation
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Navigation/Navigation/Navigation.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Navigation
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Core
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Core/Core.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Core
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.Messaging
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/Messaging/Messaging.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Messaging
          INCLUDE_SYMBOLS: true

      - name: Publish CodeMonkeys.MVVM
        uses: rohith/publish-nuget@v2.5.5
        with: 
          PROJECT_FILE_PATH: src/MVVM/MVVM.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.MVVM
          INCLUDE_SYMBOLS: true