name: Publish CodeMonkeysMVVM (branch 'master')
on:
  push:
    branches:
    - master
jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish CodeMonkeys.Core
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/Core/Core.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Core
      
      - name: Publish CodeMonkeys.DependencyInjection
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/DependencyInjection/DependencyInjection/DependencyInjection.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.DependencyInjection

      - name: Publish CodeMonkeys.DependencyInjection.DryIoC
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/DependencyInjection/DependencyInjection.DryIoC/DependencyInjection.DryIoC.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.DependencyInjection.DryIoC

      - name: Publish CodeMonkeys.DependencyInjection.Ninject
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/DependencyInjection/DependencyInjection.Ninject/DependencyInjection.Ninject.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.DependencyInjection.Ninject

      - name: Publish CodeMonkeys.Dialogs
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/Dialogs/Dialogs/Dialogs.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Dialogs

      - name: Publish CodeMonkeys.Dialogs.Xamarin.Forms
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/Dialogs/Dialogs.Xamarin.Forms/Dialogs.Xamarin.Forms.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Dialogs.Xamarin.Forms

      - name: Publish CodeMonkeys.Logging
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/Logging/Logging/Logging.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Logging

      - name: Publish CodeMonkeys.Logging.Batching
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/Logging/Logging.Batching/Logging.Batching.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Logging.Batching

      - name: Publish CodeMonkeys.Logging.Console
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/Logging/Logging.Console/Logging.Console.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Logging.Console

      - name: Publish CodeMonkeys.Logging.Debug
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/Logging/Logging.Debug/Logging.Debug.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Logging.Debug

      - name: Publish CodeMonkeys.Logging.File
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/Logging/Logging.File/Logging.File.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Logging.File

      - name: Publish CodeMonkeys.MVVM
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/MVVM/MVVM.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.MVVM

      - name: Publish CodeMonkeys.Messaging
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/Messaging/Messaging.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Messaging

      - name: Publish CodeMonkeys.Navigation
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/Navigation/Navigation/Navigation.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Navigation

      - name: Publish CodeMonkeys.Navigation.Xamarin.Forms
        uses: rohith/publish-nuget@v2.5.2
        with: 
          PROJECT_FILE_PATH: src/Navigation/Navigation.Xamarin.Forms/Navigation.Xamarin.Forms.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: CodeMonkeys.Navigation.Xamarin.Forms
